apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: quay.io/powercloud/ibm-powervs-block-csi-driver
    newTag: v0.0.1
  - name: k8s.gcr.io/sig-storage/csi-provisioner
    newTag: v3.0.0
  - name: k8s.gcr.io/sig-storage/csi-attacher
    newTag: v3.3.0
  - name: k8s.gcr.io/sig-storage/csi-resizer
    newTag: v1.3.0
  - name: k8s.gcr.io/sig-storage/livenessprobe
    newTag: v2.5.0
  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newTag: v2.3.0
