---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: powervs-node-role
  labels:
    app.kubernetes.io/name: ibm-powervs-block-csi-driver
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
