---
 kind: ClusterRoleBinding
 apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: powervs-csi-resizer-binding
   labels:
     app.kubernetes.io/name: ibm-powervs-block-csi-driver
 subjects:
   - kind: ServiceAccount
     name: powervs-csi-controller-sa
     namespace: kube-system
 roleRef:
   kind: ClusterRole
   name: powervs-external-resizer-role
   apiGroup: rbac.authorization.k8s.io
