kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: powervs-sc
provisioner: powervs.csi.ibm.com
volumeBindingMode: WaitForFirstConsumer
volumeExpansion: true
parameters:
  type: tier3
  csi.storage.k8s.io/fstype: xfs
