---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: powervs-node-role
  labels:
    {{- include "ibm-powervs-block-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
