---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: powervs-csi-resizer-binding
 labels:
   {{- include "ibm-powervs-block-csi-driver.labels" . | nindent 4 }}
subjects:
 - kind: ServiceAccount
   name: {{ .Values.controller.serviceAccount.name }}
   namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: powervs-external-resizer-role
  apiGroup: rbac.authorization.k8s.io
