---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.node.serviceAccount.name }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "ibm-powervs-block-csi-driver.labels" . | nindent 4 }}
