apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powervs-claim-{{.Iteration}}-{{.Replica}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: powervs-sc
  resources:
    requests:
      storage: 10G
