kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: powervs-sc
provisioner: powervs.csi.ibm.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: tier3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powervs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: powervs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: powervs-claim